# Generated by Django 5.0 on 2025-05-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_property_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('commercial', 'Commercial'), ('land', 'Land')], max_length=20),
        ),
    ]
