# Generated by Django 5.0 on 2025-05-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_property_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
