# Generated by Django 5.0 on 2025-05-27 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitevisit',
            name='client',
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='agent',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_site_visits', to=settings.AUTH_USER_MODEL),
        ),
    ]
