# Generated by Django 5.0 on 2025-05-29 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_alter_property_contact_phone'),
        ('site_visits', '0002_remove_sitevisit_client_alter_sitevisit_agent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitevisit',
            options={'ordering': ['-date', '-time'], 'verbose_name': 'Site Visit', 'verbose_name_plural': 'Site Visits'},
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='client_name_manual',
            field=models.CharField(blank=True, help_text='Client name if not linked to a user account', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='client_phone_manual',
            field=models.CharField(blank=True, help_text='Client phone if not linked to a user account', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='client_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='site_visits_as_client', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_visits_as_agent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_visits_for_property', to='property.property'),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
