# Generated by Django 5.2.1 on 2025-05-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Site Visit Scheduled', 'Site Visit Scheduled'), ('Site Visit Done', 'Site Visit Done'), ('Qualified', 'Qualified'), ('Proposal', 'Proposal'), ('Negotiation', 'Negotiation'), ('Converted', 'Converted'), ('Dropped', 'Dropped')], default='New', max_length=20),
        ),
    ]
