# Generated by Django 5.0 on 2025-06-09 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_status'),
        ('property', '0006_alter_property_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='property',
            field=models.ForeignKey(blank=True, help_text='The property this lead is interested in or has converted on.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.property'),
        ),
    ]
